# Generated by Django 5.1.4 on 2025-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinformation',
            old_name='address',
            new_name='location',
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='box_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='school_badge',
            field=models.ImageField(blank=True, null=True, upload_to='badges'),
        ),
    ]
