# Generated by Django 5.1.4 on 2025-01-06 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeFeesSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('Day', 'Day Student'), ('Boarding', 'Boarding Student')], default='Day', max_length=10)),
                ('breakfast_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lunch_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('boarding_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extra_class_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for extra classes (e.g., holiday or weekend classes)', max_digits=10)),
                ('term_duration_weeks', models.PositiveIntegerField(default=12, help_text='Number of weeks in a term')),
                ('total_fee', models.DecimalField(decimal_places=2, editable=False, help_text='Automatically calculated total fee', max_digits=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_settings', to='management.grade')),
            ],
            options={
                'db_table': 'grade_fee_setting',
                'db_table_comment': 'Settings for fees based on grade, student type, and optional services',
            },
        ),
    ]
