# Generated by Django 5.1.4 on 2025-01-06 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('management', '0003_gradefeessetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='Ranking_Grade',
        ),
        migrations.AlterField(
            model_name='gradefeessetting',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_settings', to='academic.grade'),
        ),
        migrations.AlterModelTable(
            name='ranking_grade',
            table='ranking_grade',
        ),
    ]
