# Generated by Django 5.1.4 on 2025-01-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_grade_ranking_grade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeFeesSetting',
        ),
    ]
