# Generated by Django 5.1.4 on 2025-02-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_of_entry',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
