# Generated by Django 5.1.4 on 2025-02-16 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_grade_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_of_entry',
            field=models.CharField(blank=True, choices=[('grade_7', 'Grade 7'), ('grade_6', 'Grade 6'), ('grade_5', 'Grade 5'), ('grade_4', 'Grade 4'), ('grade_3', 'Grade 3'), ('grade_2', 'Grade 2'), ('grade_1', 'Grade 1')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_entry',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Year must be in YYYY format.', regex='^\\d{4}$')], verbose_name='Year of Entry'),
        ),
    ]
