# Generated by Django 5.1.4 on 2025-02-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_grade_of_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_of_entry',
            field=models.CharField(blank=True, choices=[('KIN', 'Kindergarten'), ('BBY', 'Baby'), ('MID', 'Middle'), ('UPP', 'Upper'), ('TOP', 'Top'), ('grade_7', 'Grade 7'), ('grade_6', 'Grade 6'), ('grade_5', 'Grade 5'), ('grade_4', 'Grade 4'), ('grade_3', 'Grade 3'), ('grade_2', 'Grade 2'), ('grade_1', 'Grade 1')], max_length=150, null=True),
        ),
    ]
