# Generated by Django 5.2.7 on 2025-11-20 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0018_subjecttotalmark'),
        ('students', '0009_student_father_nin_student_mother_nin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assessment_topics', to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(default='41a', max_length=100)),
                ('max_score', models.PositiveIntegerField(default=5)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.examsession')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_questions', to='academic.grade')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_question', to='academic.subject')),
                ('term_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.termexamsession')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.topics')),
            ],
            options={
                'unique_together': {('term_exam', 'question_number', 'grade', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('total_score', models.PositiveIntegerField(blank=True, help_text='Total score for the subject', null=True)),
                ('max_possible', models.PositiveIntegerField(default=100, help_text='Maximum possible score')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score', max_digits=5, null=True)),
                ('exam_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academic.examsession')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_exam_result', to='academic.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_xamrsults', to='academic.subject')),
                ('question', models.ForeignKey(blank=True, help_text='Optional for subject totals', null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.question')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='assessment.topics')),
            ],
        ),
    ]
