# Generated by Django 5.2 on 2025-12-03 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(default='41a', max_length=100)),
                ('max_score', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('total_score', models.PositiveIntegerField(blank=True, help_text='Total score for the subject', null=True)),
                ('max_possible', models.PositiveIntegerField(default=100, help_text='Maximum possible score')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score', max_digits=5, null=True)),
                ('exam_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academic.examsession')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_exam_result', to='academic.grade')),
            ],
        ),
    ]
