# Generated by Django 5.1.5 on 2025-03-11 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_termexamsession_created_by_and_more'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='term_exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.termexamsession'),
            preserve_default=False,
        ),
    ]
