# Generated by Django 5.1.5 on 2025-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_question_term_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.CharField(default='41a', max_length=100),
        ),
    ]
