# Generated by Django 5.1.5 on 2025-03-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_termexamsession_created_by_and_more'),
        ('assessment', '0003_remove_question_text_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_questions', to='academic.grade'),
            preserve_default=False,
        ),
    ]
