# Generated by Django 5.1.5 on 2025-03-11 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_termexamsession_created_by_and_more'),
        ('assessment', '0004_question_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_exam_result', to='academic.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_result', to='assessment.topics'),
            preserve_default=False,
        ),
    ]
