# Generated by Django 5.1.5 on 2025-04-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_subject_grade'),
        ('assessment', '0006_alter_examresult_topic_alter_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_xamrsults', to='academic.subject'),
        ),
    ]
