# Generated by Django 5.1.5 on 2025-04-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_subject_grade'),
        ('assessment', '0007_examresult_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_question', to='academic.subject'),
        ),
    ]
