# Generated by Django 5.2.7 on 2025-12-09 08:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTuitionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('total_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
            ],
            options={
                'db_table': 'student_tuition_description',
            },
        ),
        migrations.CreateModel(
            name='TransportFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_fee',
            },
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, choices=[('T1', 'Term 1'), ('T2', 'Term 2'), ('T3', 'Term 3')], help_text='Term for this payment (used for term-by-term balances).', max_length=2, null=True)),
                ('academic_year', models.CharField(blank=True, help_text='Academic year e.g. 2025/2026', max_length=9, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online_transfer', 'Online Transfer'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Any additional notes about the payment', null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_transactions', to='academic.grade')),
            ],
            options={
                'db_table': 'fee_transaction',
                'db_table_comment': "This includes students' fees transaction data",
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OtherSchoolPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_type', models.CharField(choices=[('development', 'development'), ('sports', 'sports'), ('library', 'library'), ('laboratory', 'laboratory'), ('uniform', 'uniform'), ('examination', 'examination'), ('medical', 'medical'), ('maintenance', 'maintenance'), ('technology', 'technology'), ('admission', 'admission'), ('field_trip', 'field_trip'), ('extra_classes', 'extra_classes')], max_length=150)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(default='No Description ...')),
                ('unique_code', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_payments', to='academic.grade')),
            ],
            options={
                'db_table': 'other_school_payments',
                'db_table_comment': 'This includes other school payments data',
            },
        ),
        migrations.CreateModel(
            name='SchoolFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuitionfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hostelfee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('breakfastfee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lunchfee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.TextField(default='No Description ...')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_fees', to='academic.grade')),
            ],
            options={
                'verbose_name_plural': 'SchoolFees',
            },
        ),
    ]
