# Generated by Django 5.2 on 2025-12-03 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('assessment', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exams', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exams_sessions', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exams', to='academic.grade'),
        ),
        migrations.AddField(
            model_name='notes',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes_created', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='notes',
            name='grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes_for_grade', to='academic.grade'),
        ),
        migrations.AddField(
            model_name='notes',
            name='topics',
            field=models.ManyToManyField(related_name='notes', to='assessment.topics'),
        ),
        migrations.AddField(
            model_name='studentmarksummary',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.examsession'),
        ),
        migrations.AddField(
            model_name='studentmarksummary',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_summaries', to='academic.grade'),
        ),
        migrations.AddField(
            model_name='studentmarksummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_summaries', to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.curriculum'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='academic.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='studentmarksummary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_summaries', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='subjecttotalmark',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.examsession'),
        ),
        migrations.AddField(
            model_name='subjecttotalmark',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_totals', to='academic.grade'),
        ),
        migrations.AddField(
            model_name='subjecttotalmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_totals', to='students.student'),
        ),
        migrations.AddField(
            model_name='subjecttotalmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_totals', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='termexamsession',
            name='created_by',
            field=models.ForeignKey(help_text='Teacher who created this exam session', on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='subjecttotalmark',
            name='term_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_totals', to='academic.termexamsession'),
        ),
        migrations.AddField(
            model_name='studentmarksummary',
            name='term_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_summaries', to='academic.termexamsession'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='academic.termexamsession'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='notes',
            order_with_respect_to='subject',
        ),
        migrations.AlterOrderWithRespectTo(
            name='exam',
            order_with_respect_to='subject',
        ),
        migrations.AddIndex(
            model_name='termexamsession',
            index=models.Index(fields=['-year', 'term_name'], name='term_exam_s_year_dd7374_idx'),
        ),
        migrations.AddIndex(
            model_name='termexamsession',
            index=models.Index(fields=['term_name', 'year'], name='term_exam_s_term_na_8dbb60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='termexamsession',
            unique_together={('term_name', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='subjecttotalmark',
            unique_together={('student', 'term_exam', 'subject')},
        ),
        migrations.AddIndex(
            model_name='studentmarksummary',
            index=models.Index(fields=['student', 'term_exam'], name='academic_st_student_6d88ca_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmarksummary',
            index=models.Index(fields=['subject', 'term_exam'], name='academic_st_subject_d358b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmarksummary',
            unique_together={('student', 'term_exam', 'subject', 'exam_type')},
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('term', 'exam_type')},
        ),
    ]
