# Generated by Django 5.1.4 on 2025-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmark',
            options={'ordering': ['term', 'student__registration_id']},
        ),
        migrations.AlterModelOptions(
            name='termexamsession',
            options={'ordering': ['year', 'term_name']},
        ),
        migrations.AlterModelTableComment(
            name='termexamsession',
            table_comment='This includes term session data',
        ),
        migrations.AddField(
            model_name='termexamsession',
            name='year',
            field=models.PositiveIntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2025, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='termexamsession',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='termexamsession',
            name='term_name',
            field=models.CharField(blank=True, choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3')], max_length=10, verbose_name='Term Name'),
        ),
        migrations.AlterField(
            model_name='termexamsession',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='studentmark',
            order_with_respect_to=None,
        ),
        migrations.AlterUniqueTogether(
            name='termexamsession',
            unique_together={('term_name', 'year')},
        ),
    ]
