# Generated by Django 5.1.4 on 2025-02-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_studentmark_options_and_more'),
        ('students', '0004_alter_student_grade_of_entry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='termexamsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='termexamsession',
            name='exam_type',
            field=models.CharField(choices=[('BOT', 'Beginning of Term'), ('MOT', 'Mid of Term'), ('EOT', 'End of Term')], default='BOT', max_length=3, verbose_name='Exam Type'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='termexamsession',
            unique_together={('term_name', 'year', 'exam_type')},
        ),
        migrations.AlterModelTable(
            name='termexamsession',
            table='term_exam_session',
        ),
        migrations.CreateModel(
            name='StudentExamSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('average_marks', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_summaries', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_summaries', to='academic.termexamsession')),
            ],
            options={
                'db_table': 'student_exam_summary',
                'ordering': ['-term__year', 'term__term_name', 'student__registration_id'],
                'unique_together': {('student', 'term')},
            },
        ),
    ]
