# Generated by Django 5.1.4 on 2025-02-19 19:28

import academic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_termexamsession_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termexamsession',
            name='year',
            field=models.PositiveIntegerField(choices=academic.models.academic_year_choices, default=2025, verbose_name='Academic Year'),
        ),
    ]
