# Generated by Django 5.1.4 on 2025-02-24 06:04

import academic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_termexamsession_year'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termexamsession',
            name='created_by',
            field=models.ForeignKey(help_text='Teacher who created this exam session', on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='termexamsession',
            name='end_date',
            field=models.DateField(help_text='End date of the exam session'),
        ),
        migrations.AlterField(
            model_name='termexamsession',
            name='exam_type',
            field=models.CharField(choices=[('BOT', 'Beginning of Term'), ('MOT', 'Mid of Term'), ('EOT', 'End of Term')], help_text='Select the type of examination', max_length=3, verbose_name='Exam Type'),
        ),
        migrations.AlterField(
            model_name='termexamsession',
            name='start_date',
            field=models.DateField(help_text='Start date of the exam session'),
        ),
        migrations.AlterField(
            model_name='termexamsession',
            name='term_name',
            field=models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], help_text='Select the term for this exam session', max_length=10, verbose_name='Term Name'),
        ),
        migrations.AlterField(
            model_name='termexamsession',
            name='year',
            field=models.PositiveIntegerField(choices=academic.models.academic_year_choices, db_index=True, default=2025, help_text='Select the academic year for this exam session', verbose_name='Academic Year'),
        ),
        migrations.AddIndex(
            model_name='termexamsession',
            index=models.Index(fields=['-year', 'term_name'], name='term_exam_s_year_dd7374_idx'),
        ),
        migrations.AddIndex(
            model_name='termexamsession',
            index=models.Index(fields=['term_name', 'year', 'exam_type'], name='term_exam_s_term_na_b5a11b_idx'),
        ),
    ]
