# Generated by Django 5.2 on 2025-07-12 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_subject_grade'),
        ('students', '0004_alter_student_grade_of_entry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='term',
        ),
        migrations.CreateModel(
            name='StudentMarkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField()),
                ('max_possible', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_summaries', to='academic.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_summaries', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_summaries', to='academic.subject')),
                ('term_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_summaries', to='academic.termexamsession')),
            ],
            options={
                'verbose_name_plural': 'Student Mark Summaries',
            },
        ),
        migrations.DeleteModel(
            name='StudentExamSummary',
        ),
        migrations.DeleteModel(
            name='StudentMark',
        ),
        migrations.AddIndex(
            model_name='studentmarksummary',
            index=models.Index(fields=['student', 'term_exam'], name='academic_st_student_6d88ca_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmarksummary',
            index=models.Index(fields=['subject', 'term_exam'], name='academic_st_subject_d358b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmarksummary',
            unique_together={('student', 'term_exam', 'subject')},
        ),
    ]
